merge tutorial Intro-Sets-Functions into develop
mathbookio/mathbook pull request #74
Opened 2018-03-11 21:35 UTC by rich1126

A basic introduction to sets and functions, using only finite sets. Intention would be to split into increasingly advanced tutorials on functions and sets individually.

 Here is the link to preview the tutorial [http://mathbook.io/review/rich1126/Intro-Sets-Functions](http://mathbook.io/review/rich1126/Intro-Sets-Functions)

2018-03-12 01:33 UTC, JetJet13 requested changes
Overall, I think the tutorial is great. It was easy to follow and it thoroughly goes over the What and the How regarding functions and sets. However, there seems to be a lack of `Why` in the two sections.

If we want to differentiate the tutorials on Mathbook from the rest, its important that we try and answer the `What, Why and How` of each topic.

For example, in regards to functions and sets, the reader should be able to walk away after reading the tutorial and have a good understanding as to `Why are functions and sets important ?`

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>Most simply, a set is a collection of objects. We can think of the set of all flowers in Hawaii, or the set of whole numbers between 10 and 37. Typically, we use curly brackets (o
It looks like the div of the definition of the empty set includes an extra div which has the paragraph right under it.

![empty-set-definition](https://user-images.githubusercontent.com/8130149/37259036-6febad68-2557-11e8-8e07-3d78317f549a.jpg)

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/exercises.json
> +[
For the exercises, we should keep a consistent format when displaying the answers, which is to display the `\square` at the end of the proof/example. Here you have squared the answer itself which is not consistent with the [Tutorial Style Guide](https://github.com/JetJet13/mathbook/wiki/Tutorial-Style-Guide#end-of-proof).

Also, the order of the exercises must be ordered by difficulty in ascending order, meaning that the easiest questions will need to be at the top and the most challenging last. I could argue that finding the cardinality is easier than finding the codomain and image of g.

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "title": "Sets",
I think the title `Sets` is a little vague in my opinion. Does it make sense to give the section on sets a more explicit title, i.e. `Understanding Sets` or something similar ?

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "title": "Functions",
I think the same applies for the `Functions` section. I think a more explicit title would be best. What do you think ?

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
I noticed that you use the term `image` in one of the paragraphs near the end of the Functions section and there doesn't seem to be any definition or minor explanation of what the image of a function is which I think might throw off the reader. I Think it would be good if we were to add some small definition for `image`.

![review-mentions-image](https://user-images.githubusercontent.com/8130149/37261453-ff44cb5a-2572-11e8-9da6-f460b7706c69.jpg)

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
I also found a small typo in one of your sentences,

![functions-paragraph-typo](https://user-images.githubusercontent.com/8130149/37261413-aa2d310c-2572-11e8-88cc-51b06537933f.jpg)

2018-03-12 01:33 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
Lastly, for the definition of `Range`, in braces you put `(also commonly called the range)` which seems a little redundant. Is there a reason that you wanted to include that there ?

![range-definition](https://user-images.githubusercontent.com/8130149/37261441-e53c43c8-2572-11e8-8762-8c34848e4c5f.jpg)

2018-03-12 02:45 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>Most simply, a set is a collection of objects. We can think of the set of all flowers in Hawaii, or the set of whole numbers between 10 and 37. Typically, we use curly brackets (o
Good catch. This is fixed now.

2018-03-12 02:45 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "title": "Sets",
I totally agree. I changed this to Understanding Sets, as suggested. That seems to be the best option.

2018-03-12 02:46 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "title": "Functions",
Agree again. I changed this to "Understanding Functions" for consistency.

2018-03-12 02:48 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
That is my fault. I was going back and forth between using range and image. I changed the definition of range to also include the fact that it is commonly called the image, but I will change this instance to range for clarity.

2018-03-12 02:49 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
Great catch. Fixed.

2018-03-12 02:49 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>A function is a rule that takes elements of one set (often called <i>inputs</i>) and assigns them to elements of another set (often called <i>outputs</i>.) The first rule to alway
Sorry; mentioned above I had been going between image and range. It now says (also commonly called image.)

2018-03-12 02:50 UTC, rich1126 commented
Overall, I appreciate the feedback. I added an extra paragraph to the opening of the "Understanding Sets" section to hopefully illuminate where sets fit into everything. It's brief, so if you want me to elaborate more or add some extra information, I totally can. I did the same for functions.

2018-03-12 02:58 UTC, rich1126 commented on src/tutorials/Intro-Sets-Functions/exercises.json
> +[
I was meaning to change that order, thanks for catching that. Squares fixed, order changed.

2018-03-12 13:23 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>In any field of mathematics, it is important to be able to deal with <i>objects</i> and <i>structures</i>. At the lowest level of mathematical objects and structures are sets. Mos
I found a small typo in the definition of a subset.
![subset-definition-typo](https://user-images.githubusercontent.com/8130149/37285995-0ef8e9be-25d7-11e8-9aa9-90584cc9b4e6.jpg)

2018-03-12 13:25 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>Now that we have sets, we want to start to create, define, and communicate relationships and patterns <i>between</i> sets. Mathematics uses the language of a function to describe
Well said! 👍 
![understanding-functions-intro](https://user-images.githubusercontent.com/8130149/37286057-3eb91ca0-25d7-11e8-8b46-0a310f43f6f1.jpg)

2018-03-12 13:26 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/content.json
> +        "text": "<p>Now that we have sets, we want to start to create, define, and communicate relationships and patterns <i>between</i> sets. Mathematics uses the language of a function to describe
Also, thanks for updating the definition of Range to include `image`.
![range-definition-update](https://user-images.githubusercontent.com/8130149/37286098-60c90198-25d7-11e8-9394-694e14e2a6ff.jpg)

2018-03-12 13:28 UTC, JetJet13 commented on src/tutorials/Intro-Sets-Functions/exercises.json
> +[
Thanks for making the changes. One thing I would like to highlight is for the Challenge question, you have the square at the end of the sentence (after the `Note`), not the actual answer.

2018-03-12 13:30 UTC, JetJet13 reviewed
Your changes look good. There are just a couple small things that need tweaking.

I'll approve once they are addressed.

2018-03-13 13:00 UTC, JetJet13 approved these changes

2018-03-13 13:08 UTC, JetJet13 commented
Nice work @rich1126. I am going to merge this later today in case anyone else wants to go over it.

2018-03-14 00:32 UTC, merged